<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE actions [
<!ELEMENT actions (action)+>
<!ELEMENT action (icon | patterns | name | unique-id | command | description | directories | audio-files | image-files | other-files | text-files | video-files)*>
<!ELEMENT icon (#PCDATA)>
<!ELEMENT command (#PCDATA)>
<!ELEMENT patterns (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ATTLIST name xml:lang CDATA #IMPLIED>
<!ELEMENT unique-id (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ATTLIST description xml:lang CDATA #IMPLIED>
<!ELEMENT startup-notify EMPTY>
<!ELEMENT directories EMPTY>
<!ELEMENT audio-files EMPTY>
<!ELEMENT image-files EMPTY>
<!ELEMENT other-files EMPTY>
<!ELEMENT text-files EMPTY>
<!ELEMENT video-files EMPTY>
]>
<!--
  Copyright (c) 2005-2006 Benedikt Meurer <benny@xfce.org>

  Default thunar-uca configuration file, which gets installed system-wide.
  This should act more like an example, and is therefore kept simple.
-->
<actions>
  <action>
    <icon>utilities-terminal</icon>
    <patterns>*</patterns>
    <range/>
    <name>Open Terminal Here</name>
    <name xml:lang="uk">Відкрити термінал тут</name>
    <name xml:lang="lt">Atverti terminalą čia</name>
    <name xml:lang="ko">이 위치에서 터미널 열기</name>
    <name xml:lang="hr">Otvori terminal ovdje</name>
    <name xml:lang="am">ተርሚናል እዚህ ክፈት</name>
    <command>xfce-open --working-directory %f --launch TerminalEmulator</command>
    <description>Example for a custom action</description>
    <description xml:lang="uk">Приклад особливої дії</description>
    <description xml:lang="lt">Pasirinktinio veiksmo pavyzdys</description>
    <description xml:lang="ko">사용자 정의 동작 에제</description>
    <description xml:lang="hr">Primjer prilagođene radnje</description>
    <description xml:lang="am">የግል ተግባር ምሳሌ</description>
    <startup-notify/>
    <directories/>
  </action>
</actions>
